### ISSUE TITLE
Login errors

### ISSUE THREAD

**Issue by mikevrind** [LeonB/laracasts-dl#3]
I tried this script to download the movies (going on a long airplane ride and don't want to manually download all movies), but I keep getting the error that me login information is wrong, but they aren't :(

**Comment by saravanamystry** [comment]
Even I am facing the same issue which "mikevrind" has mentioned

**Comment by LeonB** [comment]
Issue is fixed and added some improvements. At the moment there are 808 lessons so please be careful with downloading.
